apps/accounts/urls.py
"""
This module contains the URL routing patterns for the :mod:`accounts`
app.
"""
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^search/$', views.user_search, name='user_search'),
    url(r'^update/$', views.user_update, name='user_update'),
    url(r'^user/(?P<pk>\d+)/$', views.UserDetailView.as_view(), name='user_details'),
    url(r'^questionnaires/$',
        views.ProfileView.as_view(),
        name='account_questionnaires'
        ),
    url(r'^questionnaires/status/(?P<user_id>\d+)/$',
        views.PublicQuestionnaireListView.as_view(),
        name='questionnaires_public_list'
        ),
    url(r'^questionnaires/status/$',
        views.QuestionnaireStatusListView.as_view(),
        name='questionnaires_status_list'
        ),
    url(r'^questionnaires/search/$',
        views.QuestionnaireSearchView.as_view(),
        name='staff_questionnaires_search'
        ),

]

apps/cbp/urls.py
from django.conf.urls import url

from apps.questionnaire import views

from . import views as cbp_views


urlpatterns = [
    # The 'home' route points to the list
    url(r'^view/(?P<identifier>[^/]+)/$',
        views.QuestionnaireView.as_view(url_namespace=__package__),
        name='questionnaire_details'),
    url(r'^view/(?P<identifier>[^/]+)/map/$',
        views.QuestionnaireMapView.as_view(url_namespace=__package__),
        name='questionnaire_view_map'),
    url(r'^view/(?P<identifier>[^/]+)/(?P<step>\w+)/$',
        cbp_views.questionnaire_view_step,
        name='questionnaire_view_step'),
    url(r'^edit/new/$',
        views.QuestionnaireEditView.as_view(url_namespace=__package__),
        name='questionnaire_new'),
    url(r'^edit/(?P<identifier>[^/]+)/$',
        views.QuestionnaireEditView.as_view(url_namespace=__package__),
        name='questionnaire_edit'),
    url(r'^edit/(?P<identifier>[^/]+)/(?P<step>\w+)/$',
        views.QuestionnaireStepView.as_view(url_namespace=__package__),
        name='questionnaire_new_step'),
    url(r'^search/links/$',
        views.QuestionnaireLinkSearchView.as_view(configuration_code=__package__),
        name='questionnaire_link_search'),
]

apps/qcat/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import reverse_lazy
from django.views.generic import TemplateView, RedirectView

from . import views


# The following urls are created with the locale as prefix, eg.
urlpatterns = [
    url(r'^about/$', views.about, name='about'),
    url(r'^about/imprint/$',
        TemplateView.as_view(template_name='qcat/imprint.html'),
        name='imprint'),
    url(r'^about/terms-of-agreement/$',
        TemplateView.as_view(template_name='qcat/terms-of-agreement.html'),
        name='terms-of-agreement'),
    url(r'^about/privacy-policy/$',
        TemplateView.as_view(template_name='qcat/privacy-policy.html'),
        name='privacy-policy'),
    url(r'^admin/login/?$', views.AdminLoginView.as_view(), name='admin:login'),
    # url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': views.static_sitemap},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots\.txt', TemplateView.as_view(template_name='robots.txt'))
]
# en/questionnaire
urlpatterns += i18n_patterns(
    url(r'^$', RedirectView.as_view(
        url=reverse_lazy('wocat:home'),
        permanent=False
    ), name='home'),
    url(r'^accounts/', include(('apps.accounts.urls','accounts'),namespace='accounts')),
    url(r'^api/', include(('apps.api.urls','api'),namespace='api')),
    url(r'^configuration', include(('apps.configuration.urls','configuration'), namespace='configuration')),
    url(r'^notifications/', include('apps.notifications.urls')),
    url(r'^qcat/facts_teaser', views.FactsTeaserView.as_view(), name='facts_teaser'),
    url(r'^questionnaire/', include('apps.questionnaire.urls')),
    url(r'^search/', include(('apps.search.urls','search'), namespace='search')),
    url(r'^samplemulti/', include(('apps.samplemulti.urls','search'), namespace='samplemulti')),
    url(r'^summary/', include('apps.summary.urls')),
    url(r'^unccd/', include(('apps.unccd.urls','unccd'), namespace='unccd')),
    url(r'^wocat/', include(('apps.wocat.urls','wocat'), namespace='wocat')),
    url(r'^wocat/approaches/', include(('apps.approaches.urls','approaches'),
        namespace='approaches')),
    url(r'^wocat/cca/', include(('apps.cca.urls','cca'), namespace='cca')),
    url(r'^wocat/cbp/', include(('apps.cbp.urls','cbp'), namespace='cbp')),
    url(r'^wocat/technologies/', include(('apps.technologies.urls','technologies'),
        namespace='technologies')),
    url(r'^wocat/watershed/', include(
        ('apps.watershed.urls','watershed'), namespace='watershed')),
)

urlpatterns += i18n_patterns(
    # url(r'^sample/', include(('apps.sample.urls','sample'), namespace='sample')),
    # url(r'^samplemulti/', include(('apps.samplemulti.urls','samplemulti'),
    #     namespace='samplemulti')),
    url(r'^samplemodule/',
        include(('apps.samplemodule.urls','samplemodule'), namespace='samplemodule')),
    url(r'^404/', TemplateView.as_view(template_name='404.html')),
    url(r'^500/', TemplateView.as_view(template_name='500.html')),
    url(r'^503/', TemplateView.as_view(template_name='503.html')),
) + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/questionnaire/urls.py
from django.urls import include, path
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^upload/$',
        views.generic_file_upload,
        name='file_upload'),
    url(r'^file/(?P<action>\w+)/(?P<uid>[^/]+)/$',
        views.generic_file_serve,
        name='file_serve'),
    url(r'^edit/(?P<identifier>[^/]+)/lock/$',
        views.QuestionnaireLockView.as_view(),
        name='lock_questionnaire'),
    url(r'^geo/',
        views.get_places,
        name='slm_places'),
    url(r'^update/',
        views.get_places,
        name='update_slm_places'),
    path('', include(('apps.sample.urls', 'sample'), namespace='sample')),
]

apps/wocat/urls.py
from django.urls import include, path
from django.conf.urls import url
from django.views.generic import TemplateView

from apps.questionnaire.views import QuestionnaireListView, QuestionnaireFilterView

urlpatterns = [
    url(r'^$',
        TemplateView.as_view(template_name='wocat/home.html'),
        name='home'),
    url(r'^help/questionnaire/$',
        TemplateView.as_view(template_name='wocat/help/questionnaire_introduction.html'),
        name='help_questionnaire_introduction'),
    url(r'^faq/$',
        TemplateView.as_view(template_name='wocat/faq.html'),
        name='faq'),
    url(r'^add/$',
        TemplateView.as_view(template_name='wocat/add.html'),
        name='add'),
    url(r'^list/$',
        QuestionnaireListView.as_view(configuration_code=__package__),
        name='questionnaire_list'),
    url(r'^list_partial/$',
        QuestionnaireListView.as_view(configuration_code=__package__),
        name='questionnaire_list_partial'),
    url(r'^filter/$',
        QuestionnaireFilterView.as_view(
        configuration_code=__package__), name='questionnaire_filter'),
    url(r'^filter_partial/$',
        QuestionnaireFilterView.as_view(configuration_code=__package__),
        name='questionnaire_filter_partial'),
    path('', include(('apps.accounts.urls', 'accounts'), namespace='accounts')),
    path('', include(('apps.approaches.urls', 'approaches'), namespace='approaches')),
    path('', include(('apps.sample.urls', 'sample'), namespace='sample')),
    path('', include(('apps.api.urls.v1', 'v1'), namespace='v1')),
    path('', include(('apps.samplemulti.urls', 'samplemulti'), namespace='samplemulti')),
    path('', include(('apps.samplemodule.urls', 'samplemodule'), namespace='samplemodule')),
]

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

from apps.configuration.models import Country, ValueUser
from django.urls import reverse

from .conf import settings


class User(AbstractBaseUser, PermissionsMixin):
    """
    The model representing a user of QCAT. This is basically a local
    replication of the user database of :term:`WOCAT` which handles the
    authentication. Therefore, no password is stored.

    No local users can be created, as this would lead to potential conflicts
    of the id between the WOCAT user model and this user model.

    The user model has the following fields:
        * email (varchar, acts as username)
        * firstname (varchar)
        * lastname (varchar)
        * last_login (timestamp, automatically generated)
        * date_joined (timestamp, automatically generated)
        * is_superuser (boolean)
        * password (varchar, empty)
        * language (varchar, empty)
        * wants_messages (boolean, true)

    .. todo::
        How to handle the privileges with regard to different
        configurations (e.g. moderator in WOCAT, editor in UNCCD)
    """
    email = models.EmailField(
        verbose_name='email address', unique=True, max_length=255)
    firstname = models.CharField(max_length=255, null=True, blank=True)
    lastname = models.CharField(max_length=255, null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    typo3_session_id = models.CharField(max_length=255, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    @property
    def is_active(self):
        """
        Indicates if a user account is currently active. Always returns
        True because any user in the database (and thus logged in
        through
        :class:`accounts.authentification.WocatAuthenticationBackend`)
        is considered as being active.

        Returns:
            ``bool``. Always returns ``True``.
        """
        return True

    @property
    def is_staff(self):
        """
        Handles the access to the Django administration interface.

        The following users have access to the administration interface:

            * Superusers (``is_superuser`` set to True)
            * Members of the following :term:`User Groups`:
                * :ref:`usergroups-administrators`

        Returns:
            ``bool``. Returns ``True`` if a user can access the
            administration interface, else ``False``.
        """
        if self.is_superuser is True:
            return True
        return self.groups.filter(
            name__in=['Administrators', 'Translators', 'WOCAT Secretariat']
        ).exists()

    def get_full_name(self):
        """
        A full representation of the user.

        Returns:
            ``str``. The email address of the user.
        """
        return self.email

    def get_short_name(self):
        """
        A short representation of the user.

        Returns:
            ``str``. The email address of the user.
        """
        return self.email

    def get_display_name(self):
        """
        A representation of the user for display purposes.

        Returns:
            ``str``. The display name of the user.
        """
        return '{} {}'.format(self.firstname, self.lastname)

    def get_absolute_url(self):
        """
        Detail view url of the user.
        """
        return reverse('accounts:user_details', kwargs={'pk': self.id})

    def get_questionnaires(self):
        """
        Helper function to return the questionnaires of a user along
        with his role in this membership.

        Returns:
            ``list``. A list of tuples where each entry contains the
            following elements:

            - [0]: ``string``. The role of the membership.

            - [1]: ``questionnaire.models.Questionnaire``. The
              questionnaire object.
        """
        questionnaires = []
        for membership in self.questionnairemembership_set.all():
            questionnaires.append((membership.role, membership.questionnaire))
        return questionnaires

    def get_unccd_countries(self):
        """
        Return a list of countries (value objects) related to the current user
        with relation UNCCD Focal Point.

        Returns:
            A list of countries (configuration.models.Value) for which the
            current user is a focal point.
        """
        countries = []

        for relation in self.valueuser_set.filter(
                relation=settings.CONFIGURATION_VALUEUSER_UNCCD).all():
            countries.append(relation.value)
        return countries

    def __str__(self):
        return '{} {}'.format(self.firstname, self.lastname)

    @staticmethod
    def create_new(id, email, lastname='', firstname=''):
        """
        Creates and returns a new user.

        Args:
            ``email`` (str): The email address of the user.

            ``name`` (str): The name of the user.

        Returns:
            :class:`accounts.models.User`. The newly created user.
        """
        user = User.objects.create(
            id=id, email=email, lastname=lastname, firstname=firstname)
        return user

    def update(
            self, email=None, lastname='', firstname='', usergroups=None):
        """
        Handles the one-way synchronization of the user database by
        updating the values.

        Args:
            email:
            lastname:
            firstname:
            usergroups: A list of dicts representing the usergroups as provided
              by the remote service.
        """
        if usergroups is None:
            usergroups = []
        if (email is None and lastname == self.lastname and
                firstname == self.firstname):
            return

        # TODO: Temporary test of UNCCD flagging.
        if email in settings.TEMP_UNCCD_TEST:
            usergroups.append(
                {
                    'name': 'UNCCD Focal Point',
                    'unccd_country': 'CHE',
                }
            )

        """
        UNCCD Focal Points
        {
            'name': 'UNCCD Focal Point',
            'unccd_country': 'CHE',
        }
        """
        # todo: refactoring needed. prevent passing a mutable as method argument.
        if usergroups:
            new_unccd_group = next((x for x in usergroups if x.get('name') ==
                                    settings.ACCOUNTS_UNCCD_ROLE_NAME), None)
        if not usergroups or not new_unccd_group:
            ValueUser.objects.filter(
                user=self, relation=settings.CONFIGURATION_VALUEUSER_UNCCD
            ).delete()
        else:
            country = Country.get(new_unccd_group.get('unccd_country'))
            if country is not None:
                ValueUser.objects.get_or_create(
                    value=country, user=self,
                    relation=settings.CONFIGURATION_VALUEUSER_UNCCD)

        if email is not None:
            self.email = email
        self.lastname = lastname
        self.firstname = firstname
        self.save()

apps/accounts/forms.py
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import AuthenticationForm
import floppyforms as forms


class WocatAuthenticationForm(forms.Form, AuthenticationForm):
    """
    Use floppyforms
    """
    username = forms.CharField(
        max_length=255, label=_(u"E-mail address"),
        widget=forms.TextInput(attrs={'tabindex': 1, 'autofocus': True}))
    password = forms.CharField(
        label=_("Password"), widget=forms.PasswordInput(attrs={'tabindex': 2}))

apps/accounts/templates/details.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}
{% load compress %}
{% load sekizai_tags %}

{% block bodyclass %}layout-wocat{% endblock %}
{% block navclass %}is-wocat{% endblock %}

{% block content %}
  <main class="row" role="main">
    <div class="small-12 columns">
      <h1 class="is-title">{% trans "User Details" %}</h1>
    </div>
    <section class="tech-list small-12 columns">
      <div class="tech-group">
        <h2 class="is-group">{% trans "Information" %}</h2>
        <div class="row">
          <div class="small-4 medium-3 large-2 columns"><p>{% trans "First name:" %}</p></div>
          <div class="small-8 medium-9 large-10 columns"><p>{{ detail_user.firstname }}</p></div>
        </div>
        <div class="row">
          <div class="small-4 medium-3 large-2 columns"><p>{% trans "Last name:" %}</p></div>
          <div class="small-8 medium-9 large-10 columns"><p>{{ detail_user.lastname }}</p></div>
        </div>
        {% if request.user.is_authenticated %}
          <div class="row">
            <div class="small-4 medium-3 large-2 columns"><p>{% trans "Email:" %}</p></div>
            <div class="small-8 medium-9 large-10 columns">
              <p>
                {{ detail_user.email }}
                {% if request.user == detail_user %}
                  (<a href="{% url 'notification_preferences' %}">{% trans "Notification preferences" %}</a>)
                {% endif %}
              </p>
            </div>
          </div>
        {% endif %}
      </div>
    </section>
    {% if unccd_countries %}
      <section class="tech-list small-12 columns">
        <div class="tech-group">
          <h2 class="is-group">{% trans "UNCCD national focal point" %}</h2>
          <div class="row">
            <div class="small-12 columns user-unccd-focal-point">
              <img src="{% static 'assets/img/unccd_logo.svg' %}" alt="{% trans "UNCCD" %}">
              <span>{% trans "UNCCD focal point for country:" %} <strong>
              {% for country in unccd_countries %}
                <a href="{{ country.1 }}" class="link">{{ country.0 }}</a>
              {% endfor %}
            </strong></span>
            </div>
          </div>
        </div>
      </section>
    {% endif %}
    <section class="tech-list small-12 columns">
      <div class="tech-group">
        <h2 class="is-group">{% trans "Public questionnaires" %}</h2>
        <div class="row">
          <div class="small-12 columns" id="public-questionnaires" data-url="{% url 'accounts:questionnaires_public_list' user_id=detail_user.id %}">
          </div>
        </div>
      </div>
    </section>
  </main>

  {% addtoblock 'js' %}
    {% compress js %}
      <script>
      $(function() {

        const questionnairesContainer = $('#public-questionnaires');
        const url = questionnairesContainer.data('url');
        const spinner = '<img src="{% static 'assets/img/ajax-loader.gif' %}">';

        var loadQuestionnaires = function(page) {
          questionnairesContainer.html(spinner);
          $.ajax({
            url: url + '?status=4&page=' + page
          }).done(function(data) {
            questionnairesContainer.html(data);
          });
        };

        loadQuestionnaires(1);

        questionnairesContainer.on('click', 'ul.pagination li a', function() {
          var page = getURLParameter($(this).attr('href'), 'page');
          loadQuestionnaires(page);
          return false;
        });

        function getURLParameter(url, name) {
          return (RegExp(name + '=' + '(.+?)(&|$)').exec(url)||[,null])[1];
        }
      });
      </script>
    {% endcompress %}
  {% endaddtoblock %}
{% endblock %}

apps/accounts/templates/login.html
{% extends 'base.html' %}

{% load i18n %}
{% load floppyforms %}

{% block content %}
  <main role="main">
    <div class="row large-no-gutters">
      <div class="large-12 columns">
        <h1 class="is-title">{% trans "Login" %}</h1>

        {% if next_url %}
          <div class="alert-box info is-rhythmed-2">{% trans "Please log in to access this page." %}</div>
        {% endif %}

        <form action="{{ login_url }}" method="post" class="user-login js-submit-once">
            {% csrf_token %}
            {% formrow form.username %}
            {% formrow form.password %}
            {% if form.non_field_errors %}
              {{ form.non_field_errors }}
            {% endif %}
            <input id="button_login" type="submit" name="submit"
                   class="button" value="{% trans "Login" %}"/>
        </form>

      </div>
    </div>

    <div class="row large-no-gutters is-rhythmed-3">

      <div class="large-12 columns">
        <h2 class="is-group">{% trans "No login?" %}</h2>
        <p>{% trans "If you do not yet have a login, please visit " %} <a
                      href="https://www.wocat.net/accounts/signup/"
                      class="link">{% trans "WOCAT" %}</a> {% trans " and register for a free account." %}
              </p>

        <h2 class="is-group">{% trans "Forgot your password?" %}</h2>
        <p>{% trans "Please visit " %} <a href="https://www.wocat.net/accounts/password/reset/"
                                         class="link">{% trans "WOCAT" %}</a> {% trans " and reset your password." %}
        </p>

      </div>
    </div>
  </main>

{% endblock %}

apps/accounts/templates/questionnaire_search.html
{% extends 'technologies/base.html' %}

{% load i18n %}

{% block bodyclass %}layout-technologies{% endblock %}

{% block content %}

  <div class="top-bar-search">
    <div class="row large-no-gutters">
      <form action="{% url "accounts:staff_questionnaires_search" %}" method="get" class="questionnaire-search-form">
        <input type="text" value="{{ request.GET.term }}" name="term" class="questionnaire-search">
        <input type="submit" class="search-submit button" value="Search">
      </form>
    </div>
  </div>

  <main class="row large-collapse" role="main">
    <section class="tech-list small-12 columns">
      <div class="tech-group">
        <h2 class="is-group">{% trans "Search results" %} (<span id="questionnaire-count">{{ count }}</span>)</h2>
        <div id="questionnaire-list">
          {% include "questionnaire/partial/list.html" %}
        </div>
      </div>
      <div id="pagination" class="is-rhythmed-2">
        {% include "pagination.html" %}
      </div>
    </section>
  </main>

{% endblock %}

apps/accounts/templates/questionnaire_status_list.html
{% include 'questionnaire/partial/list.html' %}

{% include "pagination.html" %}

apps/accounts/templates/questionnaires.html
{% extends 'base.html' %}

{% load compress %}
{% load i18n %}
{% load sekizai_tags %}
{% load static %}

{% block bodyclass %}layout-wocat{% endblock %}
{% block navclass %}is-wocat{% endblock %}

{% block content %}
  <main class="row" role="main">
    <div class="small-12 columns">
      <h1 class="is-title">{% trans "My SLM data" %}
        <a href="{% url 'wocat:add' %}" class="button large right">{% trans "Add SLM data" %}</a>
      </h1>
    </div>
    <div class="small-12 columns">
      <section class="tech-list small-12 columns">
        <div class="tech-group">
          <h2 class="is-group">
            {% trans "Latest notifications" %} |
            <a href="{% url 'notification_list' %}">{% trans "All notifications" %}</a>
          </h2>
          <div id="latest-notification-updates"></div>
        </div>
      </section>
    </div>
    {% if request.user.is_staff %}
      <div class="small-12 columns">
        <section class="tech-list small-12 columns">
          <div class="tech-group">
            <h2 class="is-group">{% trans "Search" %}</h2>
              <form action="{% url "accounts:staff_questionnaires_search" %}" method="get" class="questionnaire-search-form">
                <input type="search" id="search-questionnaires" name="term"
                  data-url="{% url "accounts:staff_questionnaires_search" %}"
                  placeholder="{% trans "Search questionnaires by name, compilers name or country ISO code (alpha-3, caps: https://www.iso.org/obp/ui/#search)" %}"
                  class="questionnaire-search">
                <input type="submit" class="search-submit button " value="Search">
              </form>
          </div>
        </section>
      </div>
    {% endif %}
    <div class="small-12 columns">
      {% for status, name in statuses.items %}
        <section class="tech-list small-12 columns">
          <div class="tech-group">
            <h2 class="is-group">{{ name }}</h2>
            <div class="questionnaire-list" data-status="{{ status }}">
              <div id="status-{{ status }}" class="questionnaire-status-list"></div>
            </div>
          </div>
        </section>
      {% empty %}
        <section class="tech-list small-12 columns">
        <div class="tech-group">
          <p>{% trans "No SLM data found." %}</p>
        </div>
        </section>
      {% endfor %}
    </div>
  </main>
  {% addtoblock 'js' %}
    {% compress js %}
      <script src="{% static 'notifications/js/ajaxCsrf.js' %}"></script>
      <script src="{% static 'notifications/js/notificationActions.js' %}"></script>
      <script src="{% static 'js/chosen.jquery.min.js' %}"></script>
      <script src="{% static 'js/jquery-ui.min.js' %}"></script>
      <script>
        $(document).ready(function() {

          var spinner = '<img src="{% static 'assets/img/ajax-loader.gif' %}">';
          var latestUpdatesContainer = $('#latest-notification-updates');
          var searchInput = $('#search-questionnaires');

          // initialize isRead plugin.
          latestUpdatesContainer.bindNotificationActions({
            csrfToken: '{{ csrf_token }}',
            readUrl: '{% url 'notification_read' %}',
            notificationsUrl: '{% url 'notification_partial_list' %}',
            todoUrl: '{% url 'notification_todo_list' %}',
            initialParams: '?is_teaser',
            isTeaser: true,
            questionnairesUrl: '{% url 'notification_questionnaire_logs' %}',
            user: '{{ request.user.id }}',
            spinner: spinner
          });

          // helper to execute the ajax call and replace the container with the response.
          var loadQuestionnaires = function(status, page) {
            $.ajax({
              url: '{% url 'accounts:questionnaires_status_list' %}?status=' + status + '&page=' + page,
              method: 'GET'
            }).done(function(data) {
              $('#status-' + status).html(data);
              // Initialize foundation elements (again), eg. tooltips
              $(document).foundation();
            });
          };

          // load data when initializing the dom. display a spinner, as this may require loading the configuration
          // thus may take some time.
          $('[data-status]').each(function() {
            var status = $(this).data('status');
            $('#status-' + status).html(spinner);
            loadQuestionnaires(status, 1);
          });

          // load data on click on paginator
          $('.questionnaire-list').on('click', 'ul.pagination li a', function() {
            var page = getURLParameter($(this).attr('href'), 'page');
            if (page) {
              loadQuestionnaires($(this).parents('.questionnaire-list:first').data('status'), page)
            }
            return false;
          });

          searchInput.autocomplete({
            minLength: 3,
            source: searchInput.data("url"),
            select: function( event, ui ) {
              window.location.href = ui.item.url;
            },
            open: function(event, ui) {
              $(".ui-autocomplete").append(
                "<li class='see-all'><a>{% trans "See all results... " %}</a></li>"
              );
            }
          }).autocomplete("instance")._renderItem = function(ul, item) {
            return $("<li>")
              .append(
                  "<strong>" + item.name + "</strong> (" + item.status +
                  ")<br>Compiler: " + item.compilers + " | Country: " + item.country
              ).appendTo(ul);
          };
          // For some reason, previously "focused" li is still active when
          // hovering over the added link. Remove focus class manually.
          $("body").on("mouseover", ".see-all", function() {
            $(this).parent('ul').find('li.ui-state-focus').removeClass('ui-state-focus');
          });
          $("body").on("click", ".see-all", function() {
              searchInput.parent("form").submit();
          })
        });
        function getURLParameter(url, name) {
          return (RegExp(name + '=' + '(.+?)(&|$)').exec(url)||[,null])[1];
        }
      </script>
    {% endcompress %}
  {% endaddtoblock %}
  {% addtoblock 'css' %}
    {% compress css %}
      <link href="{% static 'css/chosen.min.css' %}" rel="stylesheet">
      <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" />
    {% endcompress %}
  {% endaddtoblock %}
{% endblock %}