apps/cbp/urls.py
from django.conf.urls import url

from apps.questionnaire import views

from . import views as cbp_views


urlpatterns = [
    # The 'home' route points to the list
    url(r'^view/(?P<identifier>[^/]+)/$',
        views.QuestionnaireView.as_view(url_namespace=__package__),
        name='questionnaire_details'),
    url(r'^view/(?P<identifier>[^/]+)/map/$',
        views.QuestionnaireMapView.as_view(url_namespace=__package__),
        name='questionnaire_view_map'),
    url(r'^view/(?P<identifier>[^/]+)/(?P<step>\w+)/$',
        cbp_views.questionnaire_view_step,
        name='questionnaire_view_step'),
    url(r'^edit/new/$',
        views.QuestionnaireEditView.as_view(url_namespace=__package__),
        name='questionnaire_new'),
    url(r'^edit/(?P<identifier>[^/]+)/$',
        views.QuestionnaireEditView.as_view(url_namespace=__package__),
        name='questionnaire_edit'),
    url(r'^edit/(?P<identifier>[^/]+)/(?P<step>\w+)/$',
        views.QuestionnaireStepView.as_view(url_namespace=__package__),
        name='questionnaire_new_step'),
    url(r'^search/links/$',
        views.QuestionnaireLinkSearchView.as_view(configuration_code=__package__),
        name='questionnaire_link_search'),
]

apps/qcat/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import reverse_lazy
from django.views.generic import TemplateView, RedirectView

from . import views


# The following urls are created with the locale as prefix, eg.
urlpatterns = [
    url(r'^about/$', views.about, name='about'),
    url(r'^about/imprint/$',
        TemplateView.as_view(template_name='qcat/imprint.html'),
        name='imprint'),
    url(r'^about/terms-of-agreement/$',
        TemplateView.as_view(template_name='qcat/terms-of-agreement.html'),
        name='terms-of-agreement'),
    url(r'^about/privacy-policy/$',
        TemplateView.as_view(template_name='qcat/privacy-policy.html'),
        name='privacy-policy'),
    url(r'^admin/login/?$', views.AdminLoginView.as_view(), name='admin:login'),
    # url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': views.static_sitemap},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots\.txt', TemplateView.as_view(template_name='robots.txt'))
]
# en/questionnaire
urlpatterns += i18n_patterns(
    url(r'^$', RedirectView.as_view(
        url=reverse_lazy('wocat:home'),
        permanent=False
    ), name='home'),
    url(r'^accounts/', include(('apps.accounts.urls','accounts'),namespace='accounts')),
    url(r'^api/', include(('apps.api.urls','api'),namespace='api')),
    url(r'^configuration', include(('apps.configuration.urls','configuration'), namespace='configuration')),
    url(r'^notifications/', include('apps.notifications.urls')),
    url(r'^qcat/facts_teaser', views.FactsTeaserView.as_view(), name='facts_teaser'),
    url(r'^questionnaire/', include('apps.questionnaire.urls')),
    url(r'^search/', include(('apps.search.urls','search'), namespace='search')),
    url(r'^samplemulti/', include(('apps.samplemulti.urls','search'), namespace='samplemulti')),
    url(r'^summary/', include('apps.summary.urls')),
    url(r'^unccd/', include(('apps.unccd.urls','unccd'), namespace='unccd')),
    url(r'^wocat/', include(('apps.wocat.urls','wocat'), namespace='wocat')),
    url(r'^wocat/approaches/', include(('apps.approaches.urls','approaches'),
        namespace='approaches')),
    url(r'^wocat/cca/', include(('apps.cca.urls','cca'), namespace='cca')),
    url(r'^wocat/cbp/', include(('apps.cbp.urls','cbp'), namespace='cbp')),
    url(r'^wocat/technologies/', include(('apps.technologies.urls','technologies'),
        namespace='technologies')),
    url(r'^wocat/watershed/', include(
        ('apps.watershed.urls','watershed'), namespace='watershed')),
)

urlpatterns += i18n_patterns(
    # url(r'^sample/', include(('apps.sample.urls','sample'), namespace='sample')),
    # url(r'^samplemulti/', include(('apps.samplemulti.urls','samplemulti'),
    #     namespace='samplemulti')),
    url(r'^samplemodule/',
        include(('apps.samplemodule.urls','samplemodule'), namespace='samplemodule')),
    url(r'^404/', TemplateView.as_view(template_name='404.html')),
    url(r'^500/', TemplateView.as_view(template_name='500.html')),
    url(r'^503/', TemplateView.as_view(template_name='503.html')),
) + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/samplemulti/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from apps.questionnaire import views

from . import views as samplemulti_views


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='samplemulti/home.html'), name='home'),
    url(r'^view/(?P<identifier>[^/]+)/$',
        views.QuestionnaireView.as_view(url_namespace=__package__),
        name='questionnaire_details',
        ),
    url(r'^view/(?P<identifier>[^/]+)/(?P<step>\w+)/$',
        samplemulti_views.questionnaire_view_step,
        name='questionnaire_view_step'),
    url(r'^edit/new/$',
        views.QuestionnaireEditView.as_view(url_namespace=__package__),
        name='questionnaire_new'),
    url(r'^edit/(?P<identifier>[^/]+)/$',
        views.QuestionnaireEditView.as_view(url_namespace=__package__),
        name='questionnaire_edit'),
    url(r'^edit/(?P<identifier>[^/]+)/(?P<step>\w+)/$',
        views.QuestionnaireStepView.as_view(url_namespace=__package__),
        name='questionnaire_new_step'),
    url(r'^search/links/$',
        views.QuestionnaireLinkSearchView.as_view(configuration_code=__package__),
        name='questionnaire_link_search'),
    url(r'^list/$',
        views.QuestionnaireListView.as_view(configuration_code=__package__),
        name='questionnaire_list'),
    url(r'^list_partial/$',
        views.QuestionnaireListView.as_view(configuration_code=__package__),
        name='questionnaire_list_partial'),
]

apps/samplemulti/views.py
from django.contrib.auth.decorators import login_required

from apps.questionnaire.views import generic_questionnaire_view_step


@login_required
def questionnaire_view_step(request, identifier, step):
    """
    View rendering the form of a single step of a new SAMPLEMULTI
    questionnaire in read-only mode.
    """
    return generic_questionnaire_view_step(
        request, identifier, step, 'samplemulti',
        page_title='SAMPLEMULTI')

apps/samplemulti/templates/samplemulti/base.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}

{% block title %}SAMPLEMULTI{% endblock %}

{% block bodyclass %}layout-tech is-samplemulti{% endblock %}
{% block navclass %}is-samplemulti{% endblock %}

{% block header %}
  {% include "wocat/partial/top.html" with current='samplemulti' %}
{% endblock %}

{% block bottom %}
{% endblock %}

apps/samplemulti/templates/samplemulti/home.html
{% extends 'samplemulti/base.html' %}

{% load i18n %}

{% block content %}

<section class="hero" data-equalizer>
  <div class="row large-collapse" data-equalizer-watch>
    <div class="medium-4 large-5 columns">
      <h1 class="is-sample">SAMPLEMULTI</h1>
      <p class="is-large">World Overview of Conservation Approaches and Technologies</p>
      <p class="is-light">SAMPLEMULTI is an established global network of Soil and Water Conservation (SWC) specialists, dedicated to sustainable land management (SLM). </p>
      <a href="{% url 'samplemulti:questionnaire_new' %}" class="button is-sample">Add a new Technology</a>
    </div>
  </div>
  <div class="hero-media" data-equalizer-watch>
    <div class="media-container is-16_9">
      <iframe src="https://player.vimeo.com/video/30426479?color=ff9933&portrait=0" width="560" height="315" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
    </div>
  </div>
</section>

<main class="row large-collapse" role="main">
  {% include "wocat/partial/search.html" with current="samplemulti" %}
  <section class="tech-list small-12 columns">
    <div class="tech-group">
      <h2 class="is-group">Last updates</h2>
      {% include "samplemulti/questionnaire/partial/list.html" %}
    </div>
  </section>
</main>

{% endblock %}